/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.Logistics;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.Logistics.Handler;
import finalprojectBackend.Organization.DonationAssignment;

import finalprojectBackend.Enterprise.Logistics.Handler;
import finalprojectBackend.Enterprise.Logistics.Vehicle;

import finalprojectUserInterface.MainJFrameForm;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author supriyaa
 */
public class HandlerSignUp extends javax.swing.JPanel {

    /**
     * Creates new form HandlerSignUp
     */
    MainJFrameForm MainLPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    
    public HandlerSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        
        for(Vehicle h: operatingSystem.getVehicleDirectory()){
            String s = h.getVehiclenum()+"| " + h.getVehiclename()+" | "+ h.getVehicletype();
            vehicle_cmb.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admintitle = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        unamelbl = new javax.swing.JLabel();
        FullNametxt = new javax.swing.JTextField();
        UsrNametxt = new javax.swing.JTextField();
        pswdlbl = new javax.swing.JLabel();
        Passtxt = new javax.swing.JPasswordField();
        addresslbl = new javax.swing.JLabel();
        Add_txt = new javax.swing.JTextField();
        City_lbl = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        State_lbl = new javax.swing.JLabel();
        Zip_lbl = new javax.swing.JLabel();
        Statetxt = new javax.swing.JTextField();
        Ziptxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        Genderlbl = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        telenum_lbl = new javax.swing.JLabel();
        genderCmb = new javax.swing.JComboBox<>();
        dob_lbl = new javax.swing.JLabel();
        telenum_txt = new javax.swing.JTextField();
        vehnum_lbl = new javax.swing.JLabel();
        dob_txt = new javax.swing.JTextField();
        vehicle_cmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admintitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        admintitle.setForeground(new java.awt.Color(0, 51, 51));
        admintitle.setText("Create Handler Profile");
        jPanel1.add(admintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        Namelbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Namelbl.setText("Name:");
        jPanel1.add(Namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 20));

        unamelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        unamelbl.setText("Username:");
        jPanel1.add(unamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));
        jPanel1.add(FullNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 216, -1));
        jPanel1.add(UsrNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 216, -1));

        pswdlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pswdlbl.setText("Password:");
        jPanel1.add(pswdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));
        jPanel1.add(Passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 216, -1));

        addresslbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addresslbl.setText("Address:");
        jPanel1.add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));
        jPanel1.add(Add_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 216, -1));

        City_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        City_lbl.setText("City:");
        jPanel1.add(City_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 216, -1));

        State_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        State_lbl.setText("State:");
        jPanel1.add(State_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        Zip_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Zip_lbl.setText("Zip Code:");
        jPanel1.add(Zip_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));
        jPanel1.add(Statetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 216, -1));
        jPanel1.add(Ziptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 215, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 659, 87, 40));

        Genderlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Genderlbl.setText("Gender:");
        jPanel1.add(Genderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        signupBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signupBtn.setText("Sign Up");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 659, 87, 40));

        telenum_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telenum_lbl.setText("Phone no.:");
        jPanel1.add(telenum_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        genderCmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genderCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(genderCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 216, -1));

        dob_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dob_lbl.setText("Date of Birth:");
        jPanel1.add(dob_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, -1, -1));
        jPanel1.add(telenum_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 216, -1));

        vehnum_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vehnum_lbl.setText("Vehicle:");
        jPanel1.add(vehnum_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 604, -1, 20));
        jPanel1.add(dob_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 216, 27));

        vehicle_cmb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(vehicle_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 216, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/delivery.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, 2310, 1300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        String address = Add_txt.getText() + txtCity.getText() + Statetxt.getText() + Ziptxt.getText();
        //uname, pswd, id, name, add, gender, telenum, dob
        //(txtFullName.getText(), txtNo.getText(), address, txtUsrName.getText(), txtPass.getText());

        Handler handler = new Handler(UsrNametxt.getText(), Passtxt.getText(), "idid", FullNametxt.getText(), address,genderCmb.getSelectedItem().toString(), telenum_txt.getText(), new Date(),operatingSystem.getVehicleByNumber(vehicle_cmb.getSelectedItem().toString()));
        System.out.println("handler " + handler.getVehicle().getVehiclename());
        operatingSystem.addHandler(handler);
        dB4OUtility.storeSystem(operatingSystem);

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
        //        if (txtFullName.getText().equals("") || txtUsrName.getText().equals("") || txtPass.getText().equals("") || txtNo.getText().equals("")
            //            || txtAdd.getText().equals("") || txtCity.getText().equals("") || txtState.getText().equals("") || txtZip.getText().equals("")) {
            //
            //            JOptionPane.showMessageDialog(this, "All fields are mandatory.");
            //        } else if (!name_chk.getText().equals("") || !telenum_chk.getText().equals("") || !add_chk.getText().equals("") || !city_chk.getText().equals("")
            //            || !state_chk.getText().equals("") || !zip_chk.getText().equals("")) {
            //
            //            JOptionPane.showMessageDialog(this, "Invalid value(s) entered.");
            //        }
            //        else{
            //            Address add = new Address(txtAdd.getText(), txtCity.getText(), txtState.getText(), Integer.parseInt(txtZip.getText()));
            //
            //            Customer cus =new Customer(txtUsrName.getText(), txtPass.getText(), new CustomerRole(),txtNo.getText(), txtFullName.getText(), add);
            //            system.addCustomer(cus);
            //
            //            dB4OUtility.storeSystem(system);
            //            JOptionPane.showMessageDialog(this, "Customer information saved.");
            //            MainJFrame cust = new MainJFrame();
            //            ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
            //            cust.setVisible(true);
            //        }
    }//GEN-LAST:event_signupBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add_txt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel City_lbl;
    private javax.swing.JTextField FullNametxt;
    private javax.swing.JLabel Genderlbl;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JPasswordField Passtxt;
    private javax.swing.JLabel State_lbl;
    private javax.swing.JTextField Statetxt;
    private javax.swing.JTextField UsrNametxt;
    private javax.swing.JLabel Zip_lbl;
    private javax.swing.JTextField Ziptxt;
    private javax.swing.JLabel addresslbl;
    private javax.swing.JLabel admintitle;
    private javax.swing.JLabel dob_lbl;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JComboBox<String> genderCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pswdlbl;
    private javax.swing.JButton signupBtn;
    private javax.swing.JLabel telenum_lbl;
    private javax.swing.JTextField telenum_txt;
    private javax.swing.JTextField txtCity;
    private javax.swing.JLabel unamelbl;
    private javax.swing.JComboBox<String> vehicle_cmb;
    private javax.swing.JLabel vehnum_lbl;
    // End of variables declaration//GEN-END:variables
}
