/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.Logistics;

/**
 *
 * @author supriyaa
 */
public class VehicleSignUp extends javax.swing.JPanel {

    /**
     * Creates new form VehicleSignUp
     */
    public VehicleSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admintitle = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        VehicleTxt = new javax.swing.JTextField();
        VehNumlbl = new javax.swing.JLabel();
        VehNumtxt = new javax.swing.JTextField();
        Address_lbl = new javax.swing.JLabel();
        TypeVehtxt = new javax.swing.JTextField();
        DescLbl = new javax.swing.JLabel();
        Desctxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        SignUpbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admintitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        admintitle.setText("Create Vehicle Profile");
        jPanel1.add(admintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        NameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NameLbl.setText("Vehicle Name:");
        jPanel1.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        VehicleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleTxtActionPerformed(evt);
            }
        });
        VehicleTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VehicleTxtKeyReleased(evt);
            }
        });
        jPanel1.add(VehicleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 177, -1));

        VehNumlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VehNumlbl.setText("Vehicle Number:");
        jPanel1.add(VehNumlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        VehNumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehNumtxtActionPerformed(evt);
            }
        });
        jPanel1.add(VehNumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 177, -1));

        Address_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Address_lbl.setText("Vehicle Type:");
        jPanel1.add(Address_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        TypeVehtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeVehtxtActionPerformed(evt);
            }
        });
        TypeVehtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TypeVehtxtKeyReleased(evt);
            }
        });
        jPanel1.add(TypeVehtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 177, -1));

        DescLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DescLbl.setText("Description:");
        jPanel1.add(DescLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        Desctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesctxtActionPerformed(evt);
            }
        });
        Desctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DesctxtKeyReleased(evt);
            }
        });
        jPanel1.add(Desctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 177, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 87, 40));

        SignUpbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SignUpbtn.setText("Sign Up");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 87, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/express-delivery-concept-checking-delivery-service-app-on-mobile-phone-delivery-scooter-motorcycle-with-cardboard-box-on-mobile-phone-and-city-background-vector.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -100, 2220, 1030));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1317, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VehicleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleTxtActionPerformed

    private void VehicleTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VehicleTxtKeyReleased
        // TODO add your handling code here:
        //        String nameconv = "^[a-zA-Z ]{1,17}$";
        //        Pattern pat = Pattern.compile(nameconv);
        //        Matcher mat = pat.matcher(txtFullName.getText());
        //
        //        if (!mat.matches()) {
            //            name_chk.setText("Name is incorrect");
            //        } else {
            //            name_chk.setText("");
            //        }
    }//GEN-LAST:event_VehicleTxtKeyReleased

    private void VehNumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehNumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehNumtxtActionPerformed

    private void TypeVehtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeVehtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeVehtxtActionPerformed

    private void TypeVehtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TypeVehtxtKeyReleased
        // TODO add your handling code here:

        //        String addrconv = "^[a-zA-Z0-9 ]{0,30}$";
        //        Pattern pat = Pattern.compile(addrconv);
        //        Matcher mat = pat.matcher(txtAdd.getText());
        //
        //        if (!mat.matches()) {
            //            add_chk.setText("Address is incorrect");
            //        } else {
            //            add_chk.setText("");
            //        }
    }//GEN-LAST:event_TypeVehtxtKeyReleased

    private void DesctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesctxtActionPerformed

    private void DesctxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesctxtKeyReleased
        // TODO add your handling code here:
        //        String cityconv = "^[a-zA-Z ]{0,30}$";
        //        Pattern pat = Pattern.compile(cityconv);
        //        Matcher mat = pat.matcher(txtCity.getText());
        //
        //        if (!mat.matches()) {
            //            city_chk.setText("City is incorrect");
            //        } else {
            //            city_chk.setText("");
            //        }
    }//GEN-LAST:event_DesctxtKeyReleased

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed

        MainFrameForm suc = new MainFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        // TODO add your handling code here:
        //String address = txtType.getText() + txtDesc.getText() + txtState.getText() + txtZip.getText();
        //String vehname, String vehnum, String vtype, String description
        //SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");
        Vehicle vehicle = new Vehicle(VehicleTxt.getText(),VehNumtxt.getText(),TypeVehtxt.getText(),Desctxt.getText());

        ecoSystem.addVehicle(vehicle);
        dB4OUtil.storeSystem(ecoSystem);

        MainFrameForm suc = new MainFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
        //        if (txtFullName.getText().equals("") || txtUsrName.getText().equals("") || txtPass.getText().equals("") || txtNo.getText().equals("")
            //            || txtAdd.getText().equals("") || txtCity.getText().equals("") || txtState.getText().equals("") || txtZip.getText().equals("")) {
            //
            //            JOptionPane.showMessageDialog(this, "All fields are mandatory.");
            //        } else if (!name_chk.getText().equals("") || !telenum_chk.getText().equals("") || !add_chk.getText().equals("") || !city_chk.getText().equals("")
            //            || !state_chk.getText().equals("") || !zip_chk.getText().equals("")) {
            //
            //            JOptionPane.showMessageDialog(this, "Invalid value(s) entered.");
            //        }
        //        else{
            //            Address add = new Address(txtAdd.getText(), txtCity.getText(), txtState.getText(), Integer.parseInt(txtZip.getText()));
            //
            //            Customer cus =new Customer(txtUsrName.getText(), txtPass.getText(), new CustomerRole(),txtNo.getText(), txtFullName.getText(), add);
            //            system.addCustomer(cus);
            //
            //            dB4OUtil.storeSystem(system);
            //            JOptionPane.showMessageDialog(this, "Customer information saved.");
            //            MainJFrame cust = new MainJFrame();
            //            ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
            //            cust.setVisible(true);
            //        }
    }//GEN-LAST:event_SignUpbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_lbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel DescLbl;
    private javax.swing.JTextField Desctxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JTextField TypeVehtxt;
    private javax.swing.JLabel VehNumlbl;
    private javax.swing.JTextField VehNumtxt;
    private javax.swing.JTextField VehicleTxt;
    private javax.swing.JLabel admintitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
