/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprojectUserInterface;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectUserInterface.Administration.AdminMainPage;
import finalprojectUserInterface.OrganBankInterface.DonarBankLandingPage;
import finalprojectUserInterface.HealthcareInterface.HospitalLandingPage;
import finalprojectUserInterface.ClinicalInterface.MainLabCoverPage;
import finalprojectUserInterface.SupplyChainInterface.LogisticsFrontPage;



import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;
import javax.swing.*;
import java.awt.*;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
/**
 *
 * @author supriyaa
 */
public class MainJFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrameForm
     */
    
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility = DB4OUtility.getInstance();
    
    ImageIcon myImage;

    public ImageIcon setIcon(String m) {
        if (m != null) {
            myImage = new ImageIcon(m);
        }
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(442, 266, Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        return i;

    }
    
    public MainJFrameForm() {
        initComponents();
        this.setSize(1200, 750);
        this.operatingSystem = dB4OUtility.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPageSplit = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        LogisticsPanel = new javax.swing.JPanel();
        Logicon_lbl = new javax.swing.JLabel();
        Log_lbl = new javax.swing.JLabel();
        donorPanel = new javax.swing.JPanel();
        Donobankicon_lbl = new javax.swing.JLabel();
        DonorBank_lbl = new javax.swing.JLabel();
        LabPanel = new javax.swing.JPanel();
        labicon_lbl = new javax.swing.JLabel();
        Lab_lbl = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        Adminicon_lbl = new javax.swing.JLabel();
        Admin_lbl = new javax.swing.JLabel();
        HospitalPanel = new javax.swing.JPanel();
        Hosicon_lbl = new javax.swing.JLabel();
        Hospital_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        OrganTitle = new javax.swing.JLabel();
        closelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(0, 48, 73));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogisticsPanel.setBackground(new java.awt.Color(252, 191, 73));
        LogisticsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogisticsPaneljPanel4MouseClicked(evt);
            }
        });

        Logicon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/icons8-progress-indicator-50.png"))); // NOI18N

        Log_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Log_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Log_lbl.setForeground(new java.awt.Color(51, 51, 51));
        Log_lbl.setText("Supply Chain");

        javax.swing.GroupLayout LogisticsPanelLayout = new javax.swing.GroupLayout(LogisticsPanel);
        LogisticsPanel.setLayout(LogisticsPanelLayout);
        LogisticsPanelLayout.setHorizontalGroup(
            LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsPanelLayout.createSequentialGroup()
                .addComponent(Logicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_lbl)
                .addGap(0, 217, Short.MAX_VALUE))
        );
        LogisticsPanelLayout.setVerticalGroup(
            LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsPanelLayout.createSequentialGroup()
                .addComponent(Logicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogisticsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Log_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(LogisticsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 370, 50));

        donorPanel.setBackground(new java.awt.Color(252, 191, 73));
        donorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donorPanelMouseClicked(evt);
            }
        });

        Donobankicon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/icons8-add-to-favorites-50.png"))); // NOI18N

        DonorBank_lbl.setBackground(new java.awt.Color(51, 51, 51));
        DonorBank_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DonorBank_lbl.setForeground(new java.awt.Color(51, 51, 51));
        DonorBank_lbl.setText("Organ Bank");

        javax.swing.GroupLayout donorPanelLayout = new javax.swing.GroupLayout(donorPanel);
        donorPanel.setLayout(donorPanelLayout);
        donorPanelLayout.setHorizontalGroup(
            donorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorPanelLayout.createSequentialGroup()
                .addComponent(Donobankicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DonorBank_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 198, Short.MAX_VALUE))
        );
        donorPanelLayout.setVerticalGroup(
            donorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorPanelLayout.createSequentialGroup()
                .addComponent(Donobankicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DonorBank_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(donorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 370, -1));

        LabPanel.setBackground(new java.awt.Color(252, 191, 73));
        LabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabPanelMouseClicked(evt);
            }
        });

        labicon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/icons8-wait-50.png"))); // NOI18N

        Lab_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Lab_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lab_lbl.setForeground(new java.awt.Color(51, 51, 51));
        Lab_lbl.setText("Clinical");

        javax.swing.GroupLayout LabPanelLayout = new javax.swing.GroupLayout(LabPanel);
        LabPanel.setLayout(LabPanelLayout);
        LabPanelLayout.setHorizontalGroup(
            LabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabPanelLayout.createSequentialGroup()
                .addComponent(labicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lab_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 196, Short.MAX_VALUE))
        );
        LabPanelLayout.setVerticalGroup(
            LabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabPanelLayout.createSequentialGroup()
                .addComponent(labicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lab_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(LabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 370, 50));

        AdminPanel.setBackground(new java.awt.Color(252, 191, 73));
        AdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminPanelMouseClicked(evt);
            }
        });

        Adminicon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/icons8-approval-50.png"))); // NOI18N

        Admin_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Admin_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_lbl.setForeground(new java.awt.Color(51, 51, 51));
        Admin_lbl.setText("Administration");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addComponent(Adminicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admin_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_lbl)
                .addGap(14, 14, 14))
            .addComponent(Adminicon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 370, 50));

        HospitalPanel.setBackground(new java.awt.Color(252, 191, 73));
        HospitalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HospitalPanelMouseClicked(evt);
            }
        });

        Hosicon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/icons8-heart-plus-50.png"))); // NOI18N
        Hosicon_lbl.setMaximumSize(new java.awt.Dimension(48, 48));
        Hosicon_lbl.setMinimumSize(new java.awt.Dimension(48, 48));
        Hosicon_lbl.setPreferredSize(new java.awt.Dimension(48, 48));

        Hospital_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Hospital_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Hospital_lbl.setForeground(new java.awt.Color(51, 51, 51));
        Hospital_lbl.setText("Healthcare");

        javax.swing.GroupLayout HospitalPanelLayout = new javax.swing.GroupLayout(HospitalPanel);
        HospitalPanel.setLayout(HospitalPanelLayout);
        HospitalPanelLayout.setHorizontalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalPanelLayout.createSequentialGroup()
                .addComponent(Hosicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hospital_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 196, Short.MAX_VALUE))
        );
        HospitalPanelLayout.setVerticalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospitalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hospital_lbl)
                .addGap(14, 14, 14))
            .addComponent(Hosicon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.add(HospitalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 370, 50));

        MainPageSplit.setLeftComponent(jPanel10);

        jPanel3.setBackground(new java.awt.Color(252, 191, 73));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrganTitle.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        OrganTitle.setForeground(new java.awt.Color(51, 51, 51));
        OrganTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrganTitle.setText("NorthEast Valley LifeCare ");
        jPanel3.add(OrganTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 530, 58));

        closelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/icons8-close-50.png"))); // NOI18N
        closelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelblMouseClicked(evt);
            }
        });
        jPanel3.add(closelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 40, 58, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/healthcare_politico.gif"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 133, 1160, 780));

        MainPageSplit.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPageSplit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPageSplit)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void sendMail() {

        try {
            Properties properties = new Properties();
//            properties.put("mail.smtp.auth", "true");
//            properties.put("mail.smtp.starttls.enable", "true");
//            properties.put("mail.smtp.host", "smtp.gmail.com");
//            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.user", "username");
            
            properties.put("mail.smtp.host", "smtp.gmail.com");
            properties.put("mail.smtp.port", "25");
            properties.put("mail.debug", "true");
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.EnableSSL.enable", "true");

            properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            properties.setProperty("mail.smtp.socketFactory.fallback", "false");
            properties.setProperty("mail.smtp.port", "465");
            properties.setProperty("mail.smtp.socketFactory.port", "465");
            String myAccountEmail = "girishpillai34@gmail.com";
            //tring myAccountEmail2 = "prasadpathak4734@gmail.com";
            //String myAccountEmail3 = "supriyakommarraju@gmail.com";
            String password = "798564516565468798498jk";
            Session session;
            session = Session.getInstance(properties, new javax.mail.Authenticator() {
                @Override
                protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                    return new javax.mail.PasswordAuthentication(myAccountEmail, password);
                }
            });
            Message mailmsg = prepareMessage(session, myAccountEmail, "huntin@gmail.com", "msg", "sub");
            Transport.send(mailmsg);
// System.out.println("Successful sent");
        } catch (MessagingException ex) {
            ex.printStackTrace();
//            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private static Message prepareMessage(Session session, String myAccountEmail, String toAddress, String emailmsg, String emailsubject) {

        try {
            Message mailmsg = new MimeMessage(session);mailmsg.setFrom(new InternetAddress(myAccountEmail));mailmsg.setRecipient(Message.RecipientType.TO, new InternetAddress(toAddress));
            mailmsg.setSubject(emailsubject);mailmsg.setText(emailmsg);
            return mailmsg;
        } catch (MessagingException ex) {
            ex.printStackTrace();
              //JOptionPane.showMessageDialog(this,"Error sending mail");
//            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
        return null;

    }
    
    private void LogisticsPaneljPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogisticsPaneljPanel4MouseClicked
        // TODO add your handling code here:
        //logistics
        LogisticsFrontPage LogisticsFrontPage = new LogisticsFrontPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(LogisticsFrontPage);
    }//GEN-LAST:event_LogisticsPaneljPanel4MouseClicked

    private void donorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorPanelMouseClicked
        // TODO add your handling code here:
        //Donor Bank
        DonarBankLandingPage DonorBankLandingPage = new DonarBankLandingPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(DonorBankLandingPage);
    }//GEN-LAST:event_donorPanelMouseClicked

    private void LabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabPanelMouseClicked
        // TODO add your handling code here:
        //Laboratory
        MainLabCoverPage MainLabCoverPage = new MainLabCoverPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(MainLabCoverPage);
    }//GEN-LAST:event_LabPanelMouseClicked

    private void AdminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminPanelMouseClicked
        // TODO add your handling code here:
        //Admin
        AdminMainPage AdminPage = new AdminMainPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(AdminPage);
    }//GEN-LAST:event_AdminPanelMouseClicked

    private void HospitalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HospitalPanelMouseClicked
        // TODO add your handling code here:
        //Hospital
        HospitalLandingPage HospitalLandingPage = new HospitalLandingPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(HospitalLandingPage);
    }//GEN-LAST:event_HospitalPanelMouseClicked

    private void closelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closelblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel Admin_lbl;
    private javax.swing.JLabel Adminicon_lbl;
    private javax.swing.JLabel Donobankicon_lbl;
    private javax.swing.JLabel DonorBank_lbl;
    private javax.swing.JLabel Hosicon_lbl;
    private javax.swing.JPanel HospitalPanel;
    private javax.swing.JLabel Hospital_lbl;
    private javax.swing.JPanel LabPanel;
    private javax.swing.JLabel Lab_lbl;
    private javax.swing.JLabel Log_lbl;
    private javax.swing.JLabel Logicon_lbl;
    private javax.swing.JPanel LogisticsPanel;
    private javax.swing.JSplitPane MainPageSplit;
    private javax.swing.JLabel OrganTitle;
    private javax.swing.JLabel closelbl;
    private javax.swing.JPanel donorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labicon_lbl;
    // End of variables declaration//GEN-END:variables
}
