/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.DonarBankInterface;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.DonorBank.DonorUser;
import finalprojectBackend.Enterprise.DonorBank.DonorBank;
import finalprojectUserInterface.MainJFrameForm;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author supriyaa
 */
public class DonarBankSignUp extends javax.swing.JPanel {

    /**
     * Creates new form DonarBankSignUp
     */
    MainJFrameForm MainLPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    
    public DonarBankSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        
        for(DonorBank db: operatingSystem.getDonorBankDirectory()){
            donorbnknamecmb.addItem(db.getEnterpriseName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_admintitle = new javax.swing.JLabel();
        Name_lbl = new javax.swing.JLabel();
        FullNametxt = new javax.swing.JTextField();
        uname_lbl = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        pswd_lbl = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        addrlbl = new javax.swing.JLabel();
        Addtxt = new javax.swing.JTextField();
        Citylbl = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        Statelbl = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        Ziplbl = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        signupbtn = new javax.swing.JButton();
        genderlbl = new javax.swing.JLabel();
        gendercmb = new javax.swing.JComboBox<>();
        telenumlbl = new javax.swing.JLabel();
        telenumtxt = new javax.swing.JTextField();
        doblbl = new javax.swing.JLabel();
        dobtxt = new javax.swing.JTextField();
        donorbnknamelbl = new javax.swing.JLabel();
        donorbnknamecmb = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 204, 204));

        lbl_admintitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_admintitle.setText("Create Donor Profile");

        Name_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Name_lbl.setText("Name:");

        FullNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNametxtActionPerformed(evt);
            }
        });
        FullNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FullNametxtKeyReleased(evt);
            }
        });

        uname_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uname_lbl.setText("Username:");

        Usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametxtActionPerformed(evt);
            }
        });

        pswd_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pswd_lbl.setText("Password:");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        addrlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addrlbl.setText("Address:");

        Addtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtxtActionPerformed(evt);
            }
        });
        Addtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AddtxtKeyReleased(evt);
            }
        });

        Citylbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Citylbl.setText("City:");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });

        Statelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Statelbl.setText("State:");

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        txtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStateKeyReleased(evt);
            }
        });

        Ziplbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ziplbl.setText("Zip Code:");

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });
        txtZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZipKeyReleased(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        signupbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signupbtn.setText("Sign Up");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });

        genderlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        genderlbl.setText("Gender:");

        gendercmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gendercmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        telenumlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telenumlbl.setText("Phone no.:");

        telenumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telenumtxtActionPerformed(evt);
            }
        });
        telenumtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telenumtxtKeyReleased(evt);
            }
        });

        doblbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        doblbl.setText("Date of Birth:");

        dobtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobtxtActionPerformed(evt);
            }
        });
        dobtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobtxtKeyReleased(evt);
            }
        });

        donorbnknamelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        donorbnknamelbl.setText("Donor Bank:");

        donorbnknamecmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        donorbnknamecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorbnknamecmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(Name_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(FullNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(uname_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(pswd_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(addrlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Addtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(Citylbl)
                        .addGap(10, 10, 10)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(Statelbl)
                        .addGap(10, 10, 10)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(Ziplbl)
                        .addGap(10, 10, 10)
                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(genderlbl)
                        .addGap(12, 12, 12)
                        .addComponent(gendercmb, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(telenumlbl)
                        .addGap(18, 18, 18)
                        .addComponent(telenumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(doblbl)
                        .addGap(18, 18, 18)
                        .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(donorbnknamelbl)
                        .addGap(12, 12, 12)
                        .addComponent(donorbnknamecmb, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(signupbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lbl_admintitle)))
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_admintitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Name_lbl))
                    .addComponent(FullNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(uname_lbl))
                    .addComponent(Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(pswd_lbl))
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrlbl))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Citylbl))
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Statelbl))
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Ziplbl))
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(genderlbl))
                    .addComponent(gendercmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(telenumlbl))
                    .addComponent(telenumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(doblbl))
                    .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(donorbnknamelbl))
                    .addComponent(donorbnknamecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FullNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNametxtActionPerformed
    }//GEN-LAST:event_FullNametxtActionPerformed

    private void FullNametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FullNametxtKeyReleased
    }//GEN-LAST:event_FullNametxtKeyReleased

    private void UsernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametxtActionPerformed
    }//GEN-LAST:event_UsernametxtActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
    }//GEN-LAST:event_txtPassActionPerformed

    private void AddtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtxtActionPerformed
    }//GEN-LAST:event_AddtxtActionPerformed

    private void AddtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddtxtKeyReleased
    }//GEN-LAST:event_AddtxtKeyReleased

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
    }//GEN-LAST:event_txtCityKeyReleased

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateKeyReleased
    }//GEN-LAST:event_txtStateKeyReleased

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtZipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipKeyReleased
    }//GEN-LAST:event_txtZipKeyReleased

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        String address = Addtxt.getText() + txtCity.getText() + txtState.getText() + txtZip.getText();

        DonorUser donor = new DonorUser(Usernametxt.getText(), txtPass.getText(), "idid", FullNametxt.getText(), address, gendercmb.getSelectedItem().toString(), telenumtxt.getText(), new Date(),donorbnknamecmb.getSelectedItem().toString());

        operatingSystem.addDonor(donor);
        dB4OUtility.storeSystem(operatingSystem);

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_signupbtnActionPerformed

    private void telenumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telenumtxtActionPerformed
    }//GEN-LAST:event_telenumtxtActionPerformed

    private void telenumtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telenumtxtKeyReleased
    }//GEN-LAST:event_telenumtxtKeyReleased

    private void dobtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobtxtActionPerformed
    }//GEN-LAST:event_dobtxtActionPerformed

    private void dobtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobtxtKeyReleased
    }//GEN-LAST:event_dobtxtKeyReleased

    private void donorbnknamecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorbnknamecmbActionPerformed
    }//GEN-LAST:event_donorbnknamecmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addtxt;
    private javax.swing.JLabel Citylbl;
    private javax.swing.JTextField FullNametxt;
    private javax.swing.JLabel Name_lbl;
    private javax.swing.JLabel Statelbl;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JLabel Ziplbl;
    private javax.swing.JLabel addrlbl;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel doblbl;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JComboBox<String> donorbnknamecmb;
    private javax.swing.JLabel donorbnknamelbl;
    private javax.swing.JComboBox<String> gendercmb;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JLabel lbl_admintitle;
    private javax.swing.JLabel pswd_lbl;
    private javax.swing.JButton signupbtn;
    private javax.swing.JLabel telenumlbl;
    private javax.swing.JTextField telenumtxt;
    private javax.swing.JTextField txtCity;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZip;
    private javax.swing.JLabel uname_lbl;
    // End of variables declaration//GEN-END:variables
}
