/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprojectUserInterface.UserInterfaceMainpage;

import finalprojectUserInterface.*;

/**
 *
 * @author supriyaa
 */
public class MainJFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrameForm
     */
    public MainJFrameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        LogisticsPanel = new javax.swing.JPanel();
        Logicon_lbl = new javax.swing.JLabel();
        Log_lbl = new javax.swing.JLabel();
        donorPanel = new javax.swing.JPanel();
        Donobankicon_lbl = new javax.swing.JLabel();
        DonorBank_lbl = new javax.swing.JLabel();
        LabPanel = new javax.swing.JPanel();
        labicon_lbl = new javax.swing.JLabel();
        Lab_lbl = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        Adminicon_lbl = new javax.swing.JLabel();
        Admin_lbl = new javax.swing.JLabel();
        HospitalPanel = new javax.swing.JPanel();
        Hosicon_lbl = new javax.swing.JLabel();
        Hospital_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        OrganTitle = new javax.swing.JLabel();
        closelbl = new javax.swing.JLabel();
        gifLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogisticsPanel.setBackground(new java.awt.Color(85, 65, 118));
        LogisticsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogisticsPaneljPanel4MouseClicked(evt);
            }
        });

        Logicon_lbl.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/icons8-progress-indicator-50.png")); // NOI18N

        Log_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Log_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Log_lbl.setText("Logistics");

        javax.swing.GroupLayout LogisticsPanelLayout = new javax.swing.GroupLayout(LogisticsPanel);
        LogisticsPanel.setLayout(LogisticsPanelLayout);
        LogisticsPanelLayout.setHorizontalGroup(
            LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsPanelLayout.createSequentialGroup()
                .addComponent(Logicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 237, Short.MAX_VALUE))
        );
        LogisticsPanelLayout.setVerticalGroup(
            LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsPanelLayout.createSequentialGroup()
                .addComponent(Logicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogisticsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Log_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(LogisticsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 370, 50));

        donorPanel.setBackground(new java.awt.Color(85, 65, 118));
        donorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donorPanelMouseClicked(evt);
            }
        });

        Donobankicon_lbl.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/icons8-add-to-favorites-50.png")); // NOI18N

        DonorBank_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DonorBank_lbl.setForeground(new java.awt.Color(255, 255, 255));
        DonorBank_lbl.setText("Donor Bank");

        javax.swing.GroupLayout donorPanelLayout = new javax.swing.GroupLayout(donorPanel);
        donorPanel.setLayout(donorPanelLayout);
        donorPanelLayout.setHorizontalGroup(
            donorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorPanelLayout.createSequentialGroup()
                .addComponent(Donobankicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DonorBank_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 198, Short.MAX_VALUE))
        );
        donorPanelLayout.setVerticalGroup(
            donorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorPanelLayout.createSequentialGroup()
                .addComponent(Donobankicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DonorBank_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(donorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 370, -1));

        LabPanel.setBackground(new java.awt.Color(85, 65, 118));
        LabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabPanelMouseClicked(evt);
            }
        });

        labicon_lbl.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/icons8-wait-50.png")); // NOI18N

        Lab_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lab_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Lab_lbl.setText("Laboratory");

        javax.swing.GroupLayout LabPanelLayout = new javax.swing.GroupLayout(LabPanel);
        LabPanel.setLayout(LabPanelLayout);
        LabPanelLayout.setHorizontalGroup(
            LabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabPanelLayout.createSequentialGroup()
                .addComponent(labicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lab_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 196, Short.MAX_VALUE))
        );
        LabPanelLayout.setVerticalGroup(
            LabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabPanelLayout.createSequentialGroup()
                .addComponent(labicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lab_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(LabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 370, 50));

        AdminPanel.setBackground(new java.awt.Color(85, 65, 118));
        AdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminPanelMouseClicked(evt);
            }
        });

        Adminicon_lbl.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/icons8-approval-50.png")); // NOI18N

        Admin_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Admin_lbl.setText("Administration");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addComponent(Adminicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admin_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_lbl)
                .addGap(14, 14, 14))
            .addComponent(Adminicon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 370, 50));

        HospitalPanel.setBackground(new java.awt.Color(85, 65, 118));
        HospitalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HospitalPanelMouseClicked(evt);
            }
        });

        Hosicon_lbl.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/icons8-heart-plus-50.png")); // NOI18N
        Hosicon_lbl.setMaximumSize(new java.awt.Dimension(48, 48));
        Hosicon_lbl.setMinimumSize(new java.awt.Dimension(48, 48));
        Hosicon_lbl.setPreferredSize(new java.awt.Dimension(48, 48));

        Hospital_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Hospital_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Hospital_lbl.setText("Hospital");

        javax.swing.GroupLayout HospitalPanelLayout = new javax.swing.GroupLayout(HospitalPanel);
        HospitalPanel.setLayout(HospitalPanelLayout);
        HospitalPanelLayout.setHorizontalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalPanelLayout.createSequentialGroup()
                .addComponent(Hosicon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hospital_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 196, Short.MAX_VALUE))
        );
        HospitalPanelLayout.setVerticalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospitalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hospital_lbl)
                .addGap(14, 14, 14))
            .addComponent(Hosicon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.add(HospitalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 370, 50));

        jSplitPane1.setLeftComponent(jPanel10);

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrganTitle.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        OrganTitle.setForeground(new java.awt.Color(255, 255, 255));
        OrganTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrganTitle.setText("Organ Transplantation System");
        jPanel3.add(OrganTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 460, 58));

        closelbl.setIcon(new javax.swing.ImageIcon("/Users/supriyaa/Desktop/INFOfinalproject/info5100-java-final-project/FinalProject/src/Backgrounds/icons8-close-50.png")); // NOI18N
        closelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelblMouseClicked(evt);
            }
        });
        jPanel3.add(closelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 58, 51));

        gifLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalprojectUserInterface/UserInterfaceMainpage/image_processing20210413-17906-14nj7li.gif"))); // NOI18N
        jPanel3.add(gifLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 1020, 780));

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogisticsPaneljPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogisticsPaneljPanel4MouseClicked
        // TODO add your handling code here:
        //logistics
        MainLogisticsPage mlp = new MainLogisticsPage(this, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mlp);
    }//GEN-LAST:event_LogisticsPaneljPanel4MouseClicked

    private void donorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorPanelMouseClicked
        // TODO add your handling code here:
        //Donor Bank
        MainDonorBankPage mdp = new MainDonorBankPage(this, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mdp);
    }//GEN-LAST:event_donorPanelMouseClicked

    private void LabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabPanelMouseClicked
        // TODO add your handling code here:
        //Laboratory
        MainLabPage mlp = new MainLabPage(this, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mlp);
    }//GEN-LAST:event_LabPanelMouseClicked

    private void AdminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminPanelMouseClicked
        // TODO add your handling code here:
        //Admin
        MainAdministrationPage map = new MainAdministrationPage(this, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(map);
    }//GEN-LAST:event_AdminPanelMouseClicked

    private void HospitalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HospitalPanelMouseClicked
        // TODO add your handling code here:
        //Hospital
        MainHospitalPage mhp = new MainHospitalPage(this, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mhp);
    }//GEN-LAST:event_HospitalPanelMouseClicked

    private void closelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closelblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel Admin_lbl;
    private javax.swing.JLabel Adminicon_lbl;
    private javax.swing.JLabel Donobankicon_lbl;
    private javax.swing.JLabel DonorBank_lbl;
    private javax.swing.JLabel Hosicon_lbl;
    private javax.swing.JPanel HospitalPanel;
    private javax.swing.JLabel Hospital_lbl;
    private javax.swing.JPanel LabPanel;
    private javax.swing.JLabel Lab_lbl;
    private javax.swing.JLabel Log_lbl;
    private javax.swing.JLabel Logicon_lbl;
    private javax.swing.JPanel LogisticsPanel;
    private javax.swing.JLabel OrganTitle;
    private javax.swing.JLabel closelbl;
    private javax.swing.JPanel donorPanel;
    private javax.swing.JLabel gifLbl;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labicon_lbl;
    // End of variables declaration//GEN-END:variables
}
